### PR TITLE
Revealjs update

### PR DESCRIPTION
**Pull request by treysaddler**
Updates reveal.js version and associated files.

### CODE REVIEW

**Comment by treysaddler** [comment]
Very sad, I've been working on this for the past week and it seems you've decided to get rid of the grunt setup. Seems my timing is a bit off.

**Review by AlexanderPico — COMMENTED** [review]
The only styles in use here are the cytoscape ones. I'm hesitant to accept changes to the style without explanation and screenshots for what they fix.

**Review by AlexanderPico — APPROVED** [review]
These looks good. I might just try updating reveal directly, however, rather than via patches... Will see which is easier.

**Comment by treysaddler** [comment]
Nothing is changed in the cytoscape-presentation-1.css and protocol.css except to better interface with the relevant changes to reveal.js.

**Comment by AlexanderPico** [comment]
Yeah, it looks like we coincidentally made changes to this rarely touched code at the same time!  My goals with this intance of reveal, however, is Cytoscape-focused and simplicity. I'm preparing to use this for workshops next week and need to be sure everything is working, so changes might be conservative.   Can you point out the goals of of your changes?

**Comment by AlexanderPico** [comment]
That patch did include changes to the cytoscape styles.

**Comment by treysaddler** [comment]
Also not sure what you mean about updating reveal directly rather than via patch. I cloned the reveal.js directory and saw that there were slight structure changes for the cytoscape tutorials so I went through by hand and made sure all the relevant files were put in their proper places.

Should be able to just do an "npm install" and have it be good to go as far as packages go.

**Comment by AlexanderPico** [comment]
Well, I'm just not sure how to merge this PR...  I'm wondering how the work invovled in merging compares to me reproducing the steps you performed on your fork.

**Comment by treysaddler** [comment]
Well I spent a few days troubleshooting after updating everything to reveal.js 3.8.0.

I guess the main question is, are you set on getting rid of the grunt and scss setup? Because if so then this pull request should be closed as I did my best with the update to maintain that system, including manually merging in the custom settings that were put into the theme.scss and settings.scss to maintain the extra code for ribbons and such.

**Comment by AlexanderPico** [comment]
I'm just trying to find the shortest path to incorporate your work (which is appreciated). As it stands today, there are conflicts to be resolved. I'm not sure how much time it will take to perform the merge. It's not a one-click thing.  If I revert the scss deletion, then maybe the merge can be automatic? 

LIke I mentioned, we are going to be presenting from this site next week and the following. So, I'm thinking it might be best to perform the update (via your PR or not) after that time.

So, I'll try the quick thing now (revert my deletion). But if I can't figure out how to merge your PR quickly, then it might have to wait a few weeks.

Does that sound fair?

**Comment by AlexanderPico** [comment]
Here's the reasoning behind the deletion/simplificaiton of the stylesheets. Since this fork was created, I was only one who bothered using the system to make a couple cytoscape themes. They've essentially be untouched for years (other than my tweaks). Other users of this system are byassing stylesheets and making inline overrides. I suspect part of the reason is the complicated nature of the stylesheets. So, by blowing that all away, I'm hoping to invite other users to make use of the stylesheets.

**Comment by treysaddler** [comment]
That does make sense. It was a bit of a pain to get grunt running both on the previous version and the newer version of reveal.js. Once I did get it working, it was nice for making changes to the stylesheets, however I completely understand what you're saying about presenters with limited time not wanting to fuss around with grunt and node when they can just do an inline change.

I think I agree with you that getting rid of the scss may be the easier alternative. Let me do another commit and see if I can't make it a bit easier to merge the updates that I've made.

**Comment by AlexanderPico** [comment]
I just reverted the deletion. Your PR now has no conflicts!  I can merge it, test it, and then decide to blow away the template and source dirs again :)

**Comment by treysaddler** [comment]
Sounds good, glad I caught you before you got too far making changes.

Like I said, I've been working on this for a few days now then my git gui told me you were making changes and I wanted to catch you before my work went for naught.

I hope you're running a newer version of node as well, and let me know if you run into any problems.

**Comment by AlexanderPico** [comment]
Ok. The new reveal navigation arrows are cool! :)

I'm seeing some changes to image borders and such, but will try to fix those on top of your changes at this point.

Thanks and sorry for the hassle!

**Comment by treysaddler** [comment]
Sorry, I tried to maintain as much of the cytoscape theme as I could, but some changes were hard to tell if they were done by reveal.js or cytoscape-tutorials.

**Pull request merged**
